# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7042d0334f184d8035251c884e34d993910da1b904536a6a1e1803bd21b3b09bd818cd0759ba87a57bc7f75b09f608e42fd564faa6e90cb4c7bb5fd8958081a

test:
  secret_key_base: 9aae3470b10796c27bfd7245430d74f3238a94d19056d457e782eed602da366802432853531ed6eff801c2cb0efb828c5eeb65aba6c7c823266aeae22aa4781e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
